// Assembles web/tinycolor.js — a single self-contained classic script that
// defines `window.tinycolor` backed by the Rust port.
//
// Upstream's demo page loads the library with `<script src='tinycolor.js'>`
// and then calls `tinycolor(...)` synchronously from inline script. To keep
// index.html byte-for-byte unmodified we cannot switch it to an ES module or
// await an async init, so the wasm binary is inlined as base64 and
// instantiated with wasm-bindgen's synchronous `initSync`.
//
//   node scripts/build-demo.mjs
//
// Prerequisite:
//   wasm-pack build crates/wasm --target no-modules --out-dir ../../web/pkg \
//     --out-name tinycolor_wasm

import { readFileSync, writeFileSync, mkdirSync, copyFileSync } from "node:fs";

const UPSTREAM = process.env.UPSTREAM_DIR;
const glue = readFileSync("web/pkg/tinycolor_wasm.js", "utf8");
const wasmB64 = readFileSync("web/pkg/tinycolor_wasm_bg.wasm").toString("base64");
const api = readFileSync("shim/api.js", "utf8").replace(
  /if \(typeof module[\s\S]*$/,
  ""
);

const out = `// GENERATED by scripts/build-demo.mjs — do not edit.
//
// The Rust port of TinyColor, compiled to WebAssembly and inlined, exposed as
// the global \`tinycolor\` so upstream's own index.html runs against it
// unmodified. Built from upstream commit ${readFileSync("upstream/PINNED_COMMIT", "utf8").trim()}.
(function () {
  "use strict";

${glue}

  // Inlined wasm, so the page needs no fetch and no async init.
  var B64 = "${wasmB64}";
  function b64ToBytes(b64) {
    var bin = atob(b64);
    var bytes = new Uint8Array(bin.length);
    for (var i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
    return bytes;
  }

  wasm_bindgen.initSync({ module: b64ToBytes(B64) });

${api}

  window.tinycolor = buildTinyColorApi(wasm_bindgen.dispatch);
  window.tinycolor.__port = "rust -> wasm32";
})();
`;

mkdirSync("web/demo", { recursive: true });
writeFileSync("web/tinycolor.js", out);

if (UPSTREAM) {
  copyFileSync(`${UPSTREAM}/index.html`, "web/index.html");
  copyFileSync(`${UPSTREAM}/demo/demo.css`, "web/demo/demo.css");
  console.log("copied upstream index.html + demo/demo.css (unmodified)");
}

console.log(
  `wrote web/tinycolor.js (${(out.length / 1024 / 1024).toFixed(2)} MB, wasm inlined)`
);
